Repository googleapis/python-bigquery-reservation, pull requests merged in 2020-10, with the labels that each got.

#39 feat: implement mtls env variables mentioned in aip.dev/auth/4114
  google/cloud/bigquery/reservation_v1/services/reservation_service/async_client.py
  google/cloud/bigquery/reservation_v1/services/reservation_service/client.py
  google/cloud/bigquery/reservation_v1/services/reservation_service/transports/grpc.py
  google/cloud/bigquery/reservation_v1/services/reservation_service/transports/grpc_asyncio.py
  synth.metadata
  tests/unit/gapic/reservation_v1/test_reservation_service.py
Labels: api: bigqueryreservation, automerge, cla: yes, context: none

#43 feat: add path formatting helper methods
  docs/reservation_v1/types.rst
  google/cloud/bigquery/reservation_v1/services/reservation_service/async_client.py
  google/cloud/bigquery/reservation_v1/services/reservation_service/client.py
  google/cloud/bigquery/reservation_v1/services/reservation_service/transports/grpc.py
  google/cloud/bigquery/reservation_v1/services/reservation_service/transports/grpc_asyncio.py
  google/cloud/bigquery/reservation_v1/types/reservation.py
  scripts/fixup_reservation_v1_keywords.py
  synth.metadata
  tests/unit/gapic/reservation_v1/test_reservation_service.py
Labels: cla: yes, context: none

#38 chore(py-library): update decrypt secrets file
  scripts/decrypt-secrets.sh
  synth.metadata
Labels: api: bigqueryreservation, automerge, cla: yes, context: full

#44 chore: switch to Bazel for client generation
  synth.py
Labels: cla: yes

#51 chore(docs): update code of conduct of synthtool and templates
  .kokoro/docs/common.cfg
  .kokoro/populate-secrets.sh
  .kokoro/release/common.cfg
  .kokoro/samples/python3.6/common.cfg
  .kokoro/samples/python3.7/common.cfg
  .kokoro/samples/python3.8/common.cfg
  .kokoro/test-samples.sh
  .kokoro/trampoline.sh
  CODE_OF_CONDUCT.md
  CONTRIBUTING.rst
  docs/conf.py
  noxfile.py
  synth.metadata
Labels: automerge, cla: yes, context: partial
