Repository googleapis/python-bigquery-reservation, pull requests merged in 2020-05, with the labels that each got.

#1 refactor: updates client method names
  google/cloud/bigquery/reservation_v1/services/reservation_service/client.py
  synth.metadata
  tests/unit/reservation_v1/test_reservation_service.py
Labels: cla: yes

#5 docs: update links for product docs and API reference information
  README.rst
Labels: cla: yes

#7 feat: add helper methods to parse resource paths (via synth)
  google/cloud/bigquery/reservation_v1/services/reservation_service/client.py
  synth.metadata
  tests/unit/reservation_v1/test_reservation_service.py
Labels: cla: yes, context: partial

#9 chore: update build scripts (via synth)
  .kokoro/publish-docs.sh
  .kokoro/release.sh
  synth.metadata
Labels: automerge, cla: yes, context: partial

#12 chore: use latest sphinx
  docs/conf.py
  google/cloud/bigquery/reservation_v1/services/reservation_service/client.py
  noxfile.py
  synth.metadata
  tests/unit/reservation_v1/test_reservation_service.py
Labels: cla: yes

#14 chore: re-order methods
  google/cloud/bigquery/reservation_v1/services/reservation_service/client.py
  synth.metadata
  tests/unit/reservation_v1/test_reservation_service.py
Labels: cla: yes, context: partial
