Repository googleapis/python-bigquery-reservation, pull requests merged in 2021-02, with the labels that each got.

#77 build: migrate to flakybot
  .kokoro/test-samples.sh
  .kokoro/trampoline_v2.sh
Labels: api: bigqueryreservation, cla: yes

#78 feat: add `client_cert_source_for_mtls` argument to transports
  google/cloud/bigquery_reservation_v1/services/reservation_service/client.py
  google/cloud/bigquery_reservation_v1/services/reservation_service/transports/grpc.py
  google/cloud/bigquery_reservation_v1/services/reservation_service/transports/grpc_asyncio.py
  synth.metadata
  tests/unit/gapic/bigquery_reservation_v1/test_reservation_service.py
Labels: api: bigqueryreservation, cla: yes, context: partial

#73 chore: format docs-presubmit kokoro config
  .kokoro/docs/docs-presubmit.cfg
  synth.metadata
Labels: api: bigqueryreservation, automerge, cla: yes, context: partial

#71 chore: blacken samples directories
  synth.py
Labels: api: bigqueryreservation, automerge, cla: yes, samples

#81 chore: update templates
  .github/header-checker-lint.yml
  .trampolinerc
  noxfile.py
  samples/snippets/noxfile.py
  synth.metadata
Labels: api: bigqueryreservation, automerge, cla: yes, context: partial
