Repository googleapis/python-bigquery-reservation, pull requests merged in 2021-04, with the labels that each got.

#91 chore: prevent normalization of semver versioning
  setup.py
Labels: api: bigqueryreservation, cla: yes

#90 fix: require google-api-core >= 1.22.2
  .pre-commit-config.yaml
  noxfile.py
  setup.py
  synth.metadata
  testing/constraints-3.6.txt
Labels: api: bigqueryreservation, automerge, cla: yes, context: full

#97 chore(revert): Revert "chore: prevent normalization of semver versioning"
  setup.py
Labels: api: bigqueryreservation, cla: yes

#99 chore: add yoshi to CODEOWNERS
  .github/CODEOWNERS
Labels: api: bigqueryreservation, automerge, cla: yes
